# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d761009cc54b6a805a24e59d1f25e08b83efc9958014f24b60ac8567a0c7fce31b9cc4991b75ead159f8fd4a8c2e4a2882fe56c5aa5f974bb69c591365c02757

test:
  secret_key_base: 57ee8a6ecd22b930f4638418d07c8ac894b26c024d1e882305eea3dee0b334115cd97aa9fcb8406817a1550152df185a6e6ec84295d3cf295769372e13da48dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
